### ISSUE TITLE
Pretty Print XML

### ISSUE THREAD

**Issue by coderedart** [mitsuhiko/elementtree-rust#10]
elementtree writes xml in a single line with no formatting, so i need to use external linters (either cmdline or text editors like vscode) to format them.
so, was wondering if elementtree could export a function to pretty print xml. 

Rust doesn't have any crates that support formatting xml at the moment (atleast nothing on crates.io). with the exception of libxml2 which is technically a C FFI crate.  

the other alternative is to use crates like serde_xml_rs or quick_xml and round trip the xml through them smh. 

just newlines with indentation for child tags could go a long way.

**Comment by mitsuhiko** [comment]
The issue with pretty printing XML is that without a DTD nobody knows how to pretty print without destroying semantics. And unfortunately nobody uses DTDs any more. So it's unclear what to do here.

**Comment by coderedart** [comment]
sorry, was not aware that whitespace is significant in xml. 

I will just make a simple loop that inserts 
a newline + more indent space after  `>` and
newline + less indent space after `/>`.
