### ISSUE TITLE
Usage of namespace prefix in finding children and getting an attribute.

### ISSUE THREAD

**Issue by Ambayonyx** [mitsuhiko/elementtree-rust#11]
How should I use namespace prefix.

The code below creates: 

> Select '{tag:myns}item' in list and get '{foo}attr'
> attribute: foo1
> attribute: foo2
> attribute: foo3
> Select '{foo}item' in list and get '{foo}attr'
> Select '{tag:otherns}item' in list and get '{foo}attr'
> attribute: fooitem

I would expect the usage for `find_all()` to be identical to `get_attr()` regarding namespaces prefixes.

The code I used is:

    let mut root = Element::from_reader(r#"<?xml version="1.0"?>
    <root xmlns="tag:myns" xmlns:foo="tag:otherns">
        <list a="1" b="2" c="3">
            <item foo:attr="foo1"/>
            <item foo:attr="foo2"/>
            <item foo:attr="foo3"/>
            <foo:item foo:attr="fooitem"/>
        </list>
    </root>
    "#.as_bytes()).unwrap();

    root.set_namespace_prefix("tag:otherns", "foo");
    root.set_namespace_prefix("tag:myns", "mine");

    // The standard example
    let list = root.find("{tag:myns}list").unwrap();
    println!("Select '{{tag:myns}}item' in list and get '{{foo}}attr'");
    for child in list.find_all("{tag:myns}item") {
        println!("attribute: {}", child.get_attr("{foo}attr").unwrap());
    }

    // Using namespace prefix for all
    println!("Select '{{foo}}item' in list and get '{{foo}}attr'");
    for child in list.find_all("{foo}item") {
        println!("attribute: {}", child.get_attr("{foo}attr").unwrap());
    }

    // Using namespace prefix  only for the attribute
    println!("Select '{{tag:otherns}}item' in list and get '{{foo}}attr'");
    for child in list.find_all("{tag:otherns}item") {
        println!("attribute: {}", child.get_attr("{foo}attr").unwrap());
    }

Perhaps I'm using it incorrectly. I hope you can help me here.

**Comment by mitsuhiko** [comment]
That's indeed a bug I fixed. You always need the real namespace URL to look up things. The internal attribute map disregarded namespaces sadly.
