### ISSUE TITLE
unnecessary dbg! statements in `get_attr` function

### ISSUE THREAD

**Issue by coderedart** [mitsuhiko/elementtree-rust#16]
link to the commit : line 1122 in `src/lib.rs` https://github.com/mitsuhiko/elementtree-rust/commit/6690a8cf3ab73c36faa6e5c09e290f1423b4c00e#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1122

no description needed i think

**Comment by mitsuhiko** [comment]
Sorry for that. Fixed.
