### ISSUE TITLE
Unable to have both text and element children

### ISSUE THREAD

**Issue by KI6BDS** [mitsuhiko/elementtree-rust#7]
extern crate elementtree;

use self::elementtree::Element;

fn parse_punchout_order(body: String) -> Element {
    Element::from_reader(body.as_bytes()).unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_punchout_order_message_pom_description() {
        let xml = r#"
                            <Description xml:lang="en">
                                <ShortName>Excelsior Desk Chair</ShortName>
                                Leather Reclining Desk Chair with Padded Arms
                            </Description>
        "#;

        let desc: Element = parse_punchout_order(String::from(xml));
        let short_name = desc.find("ShortName").unwrap();
        assert_eq!("Excelsior Desk Chair", short_name.text());
        assert_eq!("Leather Reclining Desk Chair with Padded Arms", desc.text());
    }
}

fails with:
failures:

---- punchout_order::tests::test_parse_punchout_order_message_pom_description stdout ----
        thread 'punchout_order::tests::test_parse_punchout_order_message_pom_description' panicked at 'assertion failed: `(left == right)`
  left: `"Leather Reclining Desk Chair with Padded Arms"`,
 right: `"\n                                "`', src/punchout_order.rs:220:8

**Comment by mitsuhiko** [comment]
Closing this. The text is attached to the tail of the previous child in this case.
