### ISSUE TITLE
Is it possible to get the location of an attribute or Element in the source xml string?

### ISSUE THREAD

**Issue by coderedart** [mitsuhiko/elementtree-rust#9]
I am parsing an xml file and some attributes have f32 as values. if i get an error when i parse the float, i would like to point out where exactly the attribute or element is in the source xml so the user can go fix that. just wanted to know if it can be done.

**Comment by mitsuhiko** [comment]
That's not possible. The underlying reader from xml-rs does not expose position information except for errors.
